// Mock data for players
export const mockPlayers = [
  {
    id: 1,
    name: "Virat Kohli",
    country: "India",
    position: "Top Order",
    runs: 12169,
    average: 59.07,
  },
  {
    id: 2,
    name: "Joe Root",
    country: "England",
    position: "Top Order",
    runs: 10571,
    average: 50.1,
  },
  {
    id: 3,
    name: "Steve Smith",
    country: "Australia",
    position: "Top Order",
    runs: 8792,
    average: 60.08,
  },
  {
    id: 4,
    name: "Kane Williamson",
    country: "New Zealand",
    position: "Top Order",
    runs: 7572,
    average: 54.89,
  },
  {
    id: 5,
    name: "Babar Azam",
    country: "Pakistan",
    position: "Top Order",
    runs: 5089,
    average: 56.54,
  },
  {
    id: 6,
    name: "Ben Stokes",
    country: "England",
    position: "Middle Order",
    runs: 5421,
    average: 36.12,
  },
  {
    id: 7,
    name: "Shakib Al Hasan",
    country: "Bangladesh",
    position: "All-rounder",
    runs: 6657,
    average: 38.21,
  },
  {
    id: 8,
    name: "Pat Cummins",
    country: "Australia",
    position: "Bowler",
    runs: 1132,
    average: 16.6,
  },
  {
    id: 9,
    name: "Jasprit Bumrah",
    country: "India",
    position: "Bowler",
    runs: 158,
    average: 4.06,
  },
  {
    id: 10,
    name: "Trent Boult",
    country: "New Zealand",
    position: "Bowler",
    runs: 623,
    average: 10.47,
  },
  {
    id: 11,
    name: "David Warner",
    country: "Australia",
    position: "Top Order",
    runs: 8783,
    average: 45.55,
  },
  {
    id: 12,
    name: "Rohit Sharma",
    country: "India",
    position: "Top Order",
    runs: 9839,
    average: 48.78,
  },
  {
    id: 13,
    name: "Shreyas Iyer",
    country: "India",
    position: "Middle Order",
    runs: 2782,
    average: 44.15,
  },
  {
    id: 14,
    name: "Jos Buttler",
    country: "England",
    position: "Middle Order",
    runs: 4125,
    average: 40.01,
  },
  {
    id: 15,
    name: "Hardik Pandya",
    country: "India",
    position: "All-rounder",
    runs: 2090,
    average: 34.66,
  },
  {
    id: 16,
    name: "Mohammed Shami",
    country: "India",
    position: "Bowler",
    runs: 249,
    average: 7.15,
  },
  {
    id: 17,
    name: "Shaheen Afridi",
    country: "Pakistan",
    position: "Bowler",
    runs: 350,
    average: 11.2,
  },
  {
    id: 18,
    name: "Mitchell Starc",
    country: "Australia",
    position: "Bowler",
    runs: 790,
    average: 13.25,
  },
  {
    id: 19,
    name: "David Willey",
    country: "England",
    position: "All-rounder",
    runs: 520,
    average: 20.25,
  },
  {
    id: 20,
    name: "Litton Das",
    country: "Bangladesh",
    position: "Top Order",
    runs: 2580,
    average: 35.92,
  },
  {
    id: 21,
    name: "Tamim Iqbal",
    country: "Bangladesh",
    position: "Top Order",
    runs: 7800,
    average: 38.33,
  },
  {
    id: 22,
    name: "Mushfiqur Rahim",
    country: "Bangladesh",
    position: "Middle Order",
    runs: 6700,
    average: 37.29,
  },
  {
    id: 23,
    name: "Rashid Khan",
    country: "Afghanistan",
    position: "All-rounder",
    runs: 1125,
    average: 22.5,
  },
  {
    id: 24,
    name: "Mujeeb Ur Rahman",
    country: "Afghanistan",
    position: "Bowler",
    runs: 300,
    average: 10.0,
  },
  {
    id: 25,
    name: "Rahmanullah Gurbaz",
    country: "Afghanistan",
    position: "Top Order",
    runs: 1200,
    average: 30.0,
  },
  {
    id: 26,
    name: "Suryakumar Yadav",
    country: "India",
    position: "Middle Order",
    runs: 1500,
    average: 38.9,
  },
  {
    id: 27,
    name: "KL Rahul",
    country: "India",
    position: "Top Order",
    runs: 4300,
    average: 44.02,
  },
  {
    id: 28,
    name: "Temba Bavuma",
    country: "South Africa",
    position: "Top Order",
    runs: 2100,
    average: 33.33,
  },
  {
    id: 29,
    name: "Quinton de Kock",
    country: "South Africa",
    position: "Top Order",
    runs: 6000,
    average: 42.86,
  },
  {
    id: 30,
    name: "Kagiso Rabada",
    country: "South Africa",
    position: "Bowler",
    runs: 400,
    average: 9.87,
  },
  {
    id: 31,
    name: "Rassie van der Dussen",
    country: "South Africa",
    position: "Middle Order",
    runs: 3250,
    average: 49.23,
  },
  {
    id: 32,
    name: "Heinrich Klaasen",
    country: "South Africa",
    position: "Middle Order",
    runs: 2700,
    average: 41.12,
  },
  {
    id: 33,
    name: "Jason Holder",
    country: "West Indies",
    position: "All-rounder",
    runs: 2300,
    average: 29.88,
  },
  {
    id: 34,
    name: "Nicholas Pooran",
    country: "West Indies",
    position: "Middle Order",
    runs: 3100,
    average: 38.4,
  },
  {
    id: 35,
    name: "Shai Hope",
    country: "West Indies",
    position: "Top Order",
    runs: 4900,
    average: 45.45,
  },
  {
    id: 36,
    name: "Alzarri Joseph",
    country: "West Indies",
    position: "Bowler",
    runs: 350,
    average: 10.45,
  },
  {
    id: 37,
    name: "Craig Ervine",
    country: "Zimbabwe",
    position: "Top Order",
    runs: 3200,
    average: 34.7,
  },
  {
    id: 38,
    name: "Sikandar Raza",
    country: "Zimbabwe",
    position: "All-rounder",
    runs: 4100,
    average: 36.2,
  },
  {
    id: 39,
    name: "Blessing Muzarabani",
    country: "Zimbabwe",
    position: "Bowler",
    runs: 270,
    average: 7.88,
  },
  {
    id: 40,
    name: "Paul Stirling",
    country: "Ireland",
    position: "Top Order",
    runs: 5000,
    average: 38.9,
  },
  {
    id: 41,
    name: "Harry Tector",
    country: "Ireland",
    position: "Middle Order",
    runs: 2300,
    average: 40.75,
  },
  {
    id: 42,
    name: "Mark Adair",
    country: "Ireland",
    position: "All-rounder",
    runs: 800,
    average: 19.65,
  },
  {
    id: 43,
    name: "Josh Little",
    country: "Ireland",
    position: "Bowler",
    runs: 200,
    average: 8.7,
  },
  {
    id: 44,
    name: "Mohammad Nabi",
    country: "Afghanistan",
    position: "All-rounder",
    runs: 3100,
    average: 32.22,
  },
  {
    id: 45,
    name: "Najibullah Zadran",
    country: "Afghanistan",
    position: "Middle Order",
    runs: 2700,
    average: 33.21,
  },
  {
    id: 46,
    name: "Imam-ul-Haq",
    country: "Pakistan",
    position: "Top Order",
    runs: 3000,
    average: 48.22,
  },
  {
    id: 47,
    name: "Haris Rauf",
    country: "Pakistan",
    position: "Bowler",
    runs: 150,
    average: 6.1,
  },
  {
    id: 48,
    name: "Shaun Marsh",
    country: "Australia",
    position: "Top Order",
    runs: 2770,
    average: 40.35,
  },
  {
    id: 49,
    name: "Usman Khawaja",
    country: "Australia",
    position: "Top Order",
    runs: 3640,
    average: 42.18,
  },
  {
    id: 50,
    name: "Fakhar Zaman",
    country: "Pakistan",
    position: "Top Order",
    runs: 3900,
    average: 44.02,
  },
];

// Mock data for series
export const mockSeries = [
  {
    id: 1,
    name: "ICC World Cup 2023",
    players: [
      {
        id: 1,
        name: "Virat Kohli",
        runs: 765,
        ballsPlayed: 624,
        average: 95.62,
        strikeRate: 122.59,
      },
      {
        id: 5,
        name: "Babar Azam",
        runs: 550,
        ballsPlayed: 520,
        average: 61.11,
        strikeRate: 105.76,
      },
      {
        id: 3,
        name: "Steve Smith",
        runs: 498,
        ballsPlayed: 487,
        average: 62.25,
        strikeRate: 102.25,
      },
      {
        id: 6,
        name: "Ben Stokes",
        runs: 465,
        ballsPlayed: 410,
        average: 51.66,
        strikeRate: 113.41,
      },
    ],
  },
  {
    id: 2,
    name: "Ashes 2023",
    players: [
      {
        id: 2,
        name: "Joe Root",
        runs: 412,
        ballsPlayed: 386,
        average: 51.5,
        strikeRate: 106.73,
      },
      {
        id: 3,
        name: "Steve Smith",
        runs: 398,
        ballsPlayed: 372,
        average: 56.85,
        strikeRate: 106.99,
      },
      {
        id: 6,
        name: "Ben Stokes",
        runs: 375,
        ballsPlayed: 320,
        average: 46.87,
        strikeRate: 117.18,
      },
    ],
  },
  {
    id: 3,
    name: "Asia Cup 2023",
    players: [
      {
        id: 1,
        name: "Virat Kohli",
        runs: 340,
        ballsPlayed: 290,
        average: 85.0,
        strikeRate: 117.24,
      },
      {
        id: 5,
        name: "Babar Azam",
        runs: 310,
        ballsPlayed: 275,
        average: 62.0,
        strikeRate: 112.72,
      },
      {
        id: 26,
        name: "Suryakumar Yadav",
        runs: 260,
        ballsPlayed: 200,
        average: 43.33,
        strikeRate: 130.0,
      },
    ],
  },
  {
    id: 4,
    name: "Champions Trophy 2025",
    players: [
      {
        id: 12,
        name: "Rohit Sharma",
        runs: 620,
        ballsPlayed: 510,
        average: 70.5,
        strikeRate: 121.56,
      },
      {
        id: 10,
        name: "Trent Boult",
        runs: 90,
        ballsPlayed: 105,
        average: 18.0,
        strikeRate: 85.71,
      },
      {
        id: 7,
        name: "Shakib Al Hasan",
        runs: 370,
        ballsPlayed: 310,
        average: 46.25,
        strikeRate: 119.35,
      },
    ],
  },
  {
    id: 5,
    name: "Border-Gavaskar Trophy 2024",
    players: [
      {
        id: 1,
        name: "Virat Kohli",
        runs: 590,
        ballsPlayed: 480,
        average: 65.55,
        strikeRate: 122.9,
      },
      {
        id: 11,
        name: "David Warner",
        runs: 470,
        ballsPlayed: 440,
        average: 53.5,
        strikeRate: 106.82,
      },
      {
        id: 8,
        name: "Pat Cummins",
        runs: 130,
        ballsPlayed: 150,
        average: 21.66,
        strikeRate: 86.66,
      },
    ],
  },
];
